spring:
  application:
    name: "wikimedia.app"
  h2:
    console:
      enabled: true

server:
  port: 8888

app:
  wikimedia:
    url: https://stream.wikimedia.org/v2/stream/recentchange
  producer:
    topic-name: wikimedia-recent-changes
    bootstrap-servers: http://localhost:19092

logging:
  level:
    root: info
    org.springframework.web.reactive: info
    br.com.edu.wikimedia: info

