spring:
  application:
    name: "wikimedia.app"
  h2:
    console:
      enabled: true

kafka:
  bootstrap-servers: http://localhost:19092
  consumer:
    group-id: wikimedia-app-2025-01-21-20-55

server:
  port: 8888

app:
  wikimedia:
    url: https://stream.wikimedia.org/v2/stream/recentchange

logging:
  level:
    root: info
    org.springframework.web.reactive: info
    br.com.edu.wikimedia: info

